development:
  adapter: postgresql
  encoding: unicode
  database: cupcakes-world-dev
  pool: 5
  host: localhost
  username: action
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: cupcakes-world-test
  pool: 5
  host: localhost
  username: action
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: cupcakes-world-prod
  pool: 5
  host: localhost
  username: action
  password: