default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: cupcakes-world_development

test:
  <<: *default
  database: cupcakes-world_test

production:
  <<: *default
  database: cupcakes-world_production